name: Action to test and push changes up

on:
  # pull_request:
  #   branches: [ Dev ]
  push:
    branches: [ Dev ]
    
jobs:
  build_test:
    runs-on: unbuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build With Maven
      run: mvn -b package --file pom.xml

  publish-job:
    runs-on: unbutu-latest
    needs: build_test
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - run: mvn --batch-mode --update-snapshots verify
    - run: mkdir staging && cp target/*.jar staging
    - uses: actions/upload-artifact@v4
      with:
        name: Package
        path: test
